version: '3.9'

services:
    php:
        container_name: "php-fpm"
        build:
            context: ./php-fpm
        environment:
            - APP_ENV=dev
            - APP_SECRET=24e17c47430bd2044a61c131c1cf6990
        volumes:
            - ./my_first_syfy_crud_app:/var/www
        ports:
          - "9009:9000"
    mariadb:
      container_name: "mariadb"
      build:
        context: ./database
      environment:
        - MYSQL_DATABASE=symfony
        - MYSQL_USER=trunks
        - MYSQL_PASSWORD=trunks
        - MYSQL_ROOT_PASSWORD=root
      ports:
      - "3310:3306"
      volumes:
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./database/data:/var/lib/mysql

    nginx:
        container_name: "nginx"
        build:
            context: ./nginx
        volumes:
            - ./my_first_syfy_crud_app:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./logs:/var/log
        depends_on:
            - php
        ports:
            - "8090:80"